### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by dragonfire1119** [UrbanChrisy/rn-snackbar#1]
What's the difference it looks like 9gag is still updating to? https://github.com/9gag-open-source/react-native-snackbar-dialog

**Comment by UrbanChrisy** [comment]
Well the last like 5 commits have been typescript and a babel library increments, and dependcicy updates. So not actually code commits. I have added a few extra things that I wanted and a few bug fixes which i faced from using their library and is seemed like that the library was stalled so I made my own with my changes.

Few things that are different. 

I dont like flow so I removed it.
Default export was bung.

If no options were passed to the Snackbar when you would dismiss it, it would throw an error or crash. I fixed this.

Moved from travis ci to circle ci, I prefer it and its easier to use.

It uses the pre js rather than the build compiled and minified js from the dist folder, I was having problems with the build config I was using.

If you used multiple Snackbar.show() in a row it would not stack then and show them separtly, one after each other. This one does.

I added an onAutoDismiss callback when the snackbar dismisses itself. For example:
```Javascript
SnackBar.show('Your message will be sent in 5s', {
      onAutoDismiss: () => console.log('message sent example code here'),
})
```

I have probablly done some more which I cant think of atm.

I also like to make librarys in the way I want them to work, so that usally means braking changes so its not worth sending a pull req when its most likely gonna be rejected.

**Comment by dragonfire1119** [comment]
@UrbanChrisy Thanks for the reply! Some great additions Ill look at using this one! Have you thought about adding support for a icon Example: 
![](https://camo.githubusercontent.com/3f7b8aa80f042d79954c403a62682ce442cf51ae/68747470733a2f2f7261772e6769746875622e636f6d2f746573747368616c6c706173732f72656163742d6e61746976652d64726f70646f776e616c6572742f6d61737465722f73637265656e73686f74732f737563636573732e706e67)

**Comment by UrbanChrisy** [comment]
Ill work on it now, is their application to have an icon on the right as well as the right?

**Comment by dragonfire1119** [comment]
@UrbanChrisy I guess more options the better. I never thought about having it on the right but it might be a good option!
